### PR TITLE
Fix command call in postgresql server init file

### PR DESCRIPTION
**Pull request by rebost**
@baitisj please review

### CODE REVIEW

**Comment by kmoore134** [comment]
A concern I would have is that %%PREFIX%% turns into /usr/local typically. Which it looks like you intended to have things in /var/db instead.

**Comment by rebost** [comment]
Indeed, and that's what I meant it to do after checking the behaviour in plain vanilla FreeBSD ports. The bad part is that my git-fu somehow failed me and I ended up with a wrong result.
Ports under v.9.6 actually use ~${postgresql_user}/data. Good catch, thanks.
I will correct this now

**Comment by rebost** [comment]
done

**Comment by baitisj** [comment]
Drat. I screwed this up. Sigh.

**Pull request merged**
