### PR TITLE
patch for libressl build

### PR DESCRIPTION
**Pull request by digitalist**

### CODE REVIEW

**Comment by kmoore134** [comment]
Looks good, thanks!

**Comment by Sp1l** [comment]
Yep, that's OK (apart from the extra new-line :nerd:)
Has this been upstreamed?

**Comment by digitalist** [comment]
this is a part of that patch 
https://github.com/telegramdesktop/tdesktop/pull/4436
and not yet

**Comment by Sp1l** [comment]
Good!

**Pull request merged**
